---
title: "CV Sereina Graber"
author:
  firstname: Sereina M.
  lastname: Graber
  address: "Strassennamen 12, CH-8044 Zurich, Switzerland"
  position: "Data Scientist ・Public Health Researcher"
  contacts:
    - icon: fa envelope
      text: sereina.graber@gmail.com
      url: "mailto:sereina.graber@gmail.com"
    - icon: assets/icon/bi-house-fill.svg
      text: serigra.github.io
      url: https://serigra.github.io/Webpage_Quarto/
    - icon: fa brands github
      text: GitHub
      url: https://github.com/serigra
    - icon: fa brands orcid
      text: 0009-0005-2128-0827
      url: https://orcid.org/0009-0005-2128-0827
    - icon: fa brands researchgate
      text: ResearchGate
      url: https://www.researchgate.net/profile/Sereina-Graber
    - icon: fa brands linkedin
      text: LinkedIn
      url: https://www.linkedin.com/in/sereina-maria-graber-078701bb/
profile-photo: img/foto_SG.jpg
format: awesomecv-typst
---
```{r}
#| output: false
#| echo: false
library(tidyverse)
```



::: {.leftpanel}
# Experience

```{=typst}
#resume-entry(
  title: "Data Scientist & Researcher",
  location: "Zurich, Switzerland",
  date: "since 2019",
  description: "Helsana Insurance Group",
)

```

* some detail information
* more detailed information
* more detailed information

```{=typst}
#resume-entry(
  title: "Data Scientist",
  location: "Zurich, Switzerland",
  date: "2017 - 2019",
  description: "Sanitas Insurance Group",
)
```

* some detail information
* more detailed information
* more detailed information

# Education

```{=typst}
#resume-entry(
  title: "Ph.D. in Evolutionary Biology",
  location: "2017",
  date: "",
  description: "University of Zurich",
)

#resume-entry(
  title: "Master of Science - Biostatistics",
  location: "2015",
  date: "",
  description: "University of Zurich",
)

#resume-entry(
  title: "Master of Science - Biology",
  location: "2012",
  date: "",
  description: "University of Zurich",
)
```
:::

::: {.rightpanel}

# Skills





# Languages

```{r}
#| echo: false
#| fig-width: 5
#| fig-height: 1.5

col.scores <- alpha("#235347", seq(0.2,1, 0.2))

d.lang <- data.frame (
  lang = rep(c('German', 'English', 'French'), each = 5),
  score_germ = rep(c(1:5), 3),
  binary = factor(c(rep(1, 9), 0, 1, 0,0,0,0) )
)

#dot_plot <- function() {
  
 d.lang |>  
  mutate(lang = factor(lang, levels = c('French', 'English', 'German'))) |>
  mutate(color_value = ifelse(binary == 1, score_germ / 5, NA)) |>  # New line
  ggplot(aes(x=score_germ, y = lang, color = color_value)) +
  geom_point(size = 7.5, stroke = NA) +
  scale_color_gradient(low = "#23534766", high = "#235347", 
                     limits = c(0, 1.2),  # Extend the limit slightly
                     breaks = c(0, 1), 
                     labels = c("0", "1"),
                     na.value = "lightgrey") +  # Set color for binary 0
  scale_x_continuous(expand = c(0.1,0)) +
  xlab('') + 
  ylab('') + 
  theme_void() +
  theme(text = element_text(family = "sans"),
        axis.text.y = element_text(size = 21,
                                   hjust = -0),
        axis.text.x = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.y = element_blank(),
        legend.position = "none")
  
#}
```

# References

available upon request

:::




